
# vars[*].name - Must be a unique value amongst all vars
# vars[*].type - The types of variables that Ansible supports are String, Numbers, Float, List, Dictionary, and Boolean
# vars[*].ui - controls the OCP UI elements, reference https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md


# Required
name: ussfiles
displayName: z/OS USS File Management
group: zos.ibm.com
version: 0.0.3
description: >- # TODO Can also be a path to a markdown file?
  # z/OS USS File Management

  Do some cool things with z/OS files in USS using Ansible!
resources:
  - kind: TouchFile
    description: Connect to a z/OS Endpoint via Ansible and touch a file
    entrypoint: /unzipped/archive/touchfile_playbook.yml
    vars:
      - name: filepath
        displayName: File Path
        description: The path of the file to be touched on z/OS
        type: String
        xdescriptor: urn:alm:descriptor:com.tectonic.ui:text
      - name: permissions
        displayName: File Path
        description: the file rwx permissions to set on the file
        type: Number
        xdescriptor: urn:alm:descriptor:com.tectonic.ui:number
  - kind: DeleteFile
    description: Connect to a z/OS Endpoint via Ansible and delete a file
    entrypoint: /unzipped/archive/deletefile_playbook.yml
    vars:
      - name: filepath
        displayName: File Path
        description: The path of the file to be deleted on z/OS
        type: String
        xdescriptor: urn:alm:descriptor:com.tectonic.ui:text


# TODO - Optional Variables - need support in operatorcollection_types.go
short: Work with z/OS USS Files
iconPath: /unzipped/archive/icon.png #can also be an SVG
links:
  - name: Knowledge Center
  - url: 'http://ibm.biz/ibm-zos-cloud-broker-welcome'
maintainers:
  - email: zipfunc1@us.ibm.com
    name: IBM z/OS Cloud Broker Ansible-Imported Collection
provider: IBM